language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - cp demo.py /tmp/demo.py
  - python /tmp/demo.py
