language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - python setup.py bdist_wheel
  - pip install dist/deepomatic_api-*.whl
  - mkdir app
  - cp -r tests demo.py app/

# command to run tests
script:
  - pip install pytest==4.0.2 pytest-voluptuous==1.1.0 # for testing
  - python -m pytest --junit-xml=junit.xml -vv app/tests
  - python app/demo.py
