language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - python setup.py bdist_wheel
  - pip install dist/deepomatic_api-*.whl

# command to run tests
script:
  - python -c "from deepomatic.api.demo import demo; demo()"
