language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - python setup.py bdist_wheel
  - pip install dist/deepomatic_api-*.whl
  - mkdir samples
  - cp -r tests demo.py samples/

# command to run tests
script:
  - python -m pytest --junit-xml=junit.xml -vv samples/tests
  - python samples/demo.py
