dmake_version: 0.1
app_name: deepomatic-client-python
env:
  default:
    source: ${DEEPOMATIC_CONFIG_DIR}/dev.sh
    variables:
      DEEPOMATIC_APP_ID: ${TEST_CLIENTS_APP_ID}
      DEEPOMATIC_API_KEY: ${TEST_CLIENTS_API_KEY}
      DEEPOMATIC_API_URL: ${DEEPOMATIC_API_URL:-https://api.deepomatic.com}
  branches:
    master:
      source: ${DEEPOMATIC_CONFIG_DIR}/prod.sh


docker:
  base_image:
    # This first item is a YAML template named "base_image"
    # You can reuse it and override just some values with
    # "- <<: *base_image" as used below.
    - &base_image
      name: deepomatic-client-python
      variant: 2.7
      root_image: python:2.7
      copy_files:
        - requirements.txt
      install_scripts:
        - deploy/install.sh
    # Nothing changes comparing to above, except 'variant' and 'root_image'
    - <<: *base_image
      variant: 3.4
      root_image: python:3.4
    - <<: *base_image
      variant: 3.5
      root_image: python:3.5
    - <<: *base_image
      variant: 3.6
      root_image: python:3.6


services:
  - service_name: client
    config:
      docker_image:
        build: .
        base_image_variant:
          - 2.7
          - 3.4
          - 3.5
          - 3.6
    tests:
      commands:
        - python -m pytest --junit-xml=junit.xml -vv
      junit_report: junit.xml
